# Generated by Django 3.0.1 on 2020-06-07 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200607_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
